# project scope
project:
  city_name: "Milan, Italy"
  country_code: "IT"

# coordinate systems
crs:
  metric: "EPSG:32632" # UTM zone 32N (meters, used for measuring distances in Italy)
  global: "EPSG:4326" # used for H3 indexing and map visualizations

# L0 - grid
grid:
  resolution: 10 # H3 resolution approx 66m
  buffer_dist_m: 5000 # extend 5km the Milan radius

# L1 - transport
transport:
  deduplication:
    similarity_threshold: 0.7 # name similarity threshold for deduplication (0-1)
    metro_dist_m: 150 # distance threshold to consider points as metro duplicates (in meters)
    train_dist_m: 100 # distance threshold to consider points as train duplicates (in meters)
    tram_dist_m: 60 # distance threshold to consider points as tram duplicates (in meters)
  # OSM tags for extraction
  tags:
    metro:
      station: "subway"
      # railway: "subway"
    train:
      railway: "station"
    tram:
      railway: "tram_stop"
      # tram: "yes"

# L2 - pois
poi:
  deduplication:
    similarity_threshold: 0.7 # name similarity threshold for deduplication (0-1)
    distance_m: 20 # distance threshold to consider points as duplicates (in meters) between POIs
  # OSM tags for extraction
  tags:
    food_nighlife:
      amenity:
        - "retaurant"
        - "cafe"
        - "bar"
        - "pub"
        - "fast_food"
        - "ice_cream"
        - "biergarten"
        - "nightclub"
        - "food_court"
        - "bistro"
        - "canteen"
    culture_leisure:
      amenity:
        - "theatre"
        - "cinema"
        - "arts_centre"
        - "events_venue"
        - "community_centre"
        - "place_of_worship"
        - "social_centre"
        - "casino"
      tourism:
        - "museum"
        - "artwork"
        - "gallery"
        - "attraction"
        - "viewpoint"
        - "theme_park"
      leisure:
        - "park"
        - "garden"
        - "nature_reserve"
        - "stadium"
        - "sports_centre"
        - "pitch"
        - "track"
        - "fitness_centre"
    public_services:
      amenity:
        - "school'
        - "university"
        - "college"
        - "kindergarten"
        - "childcare"
        - "library"
        - "hospital"
        - "clinic"
        - "pharmacy"
        - "doctors"
        - "dentist"
        - "veterinary"
        - "post_office"
        - "townhall"
        - "police"
        - "fire_station"
        - "court_house"
    retail_shopping:
      shop:
        - "supermarket"
        - "convenience"
        - "mall"
        - "department_store"
        - "clothes"
        - "fashion"
        - "shoes"
        - "electronics"
        - "cosmetics"
        - "jewelry"
        - "watches"
        - "tailor"
        - "antiques"
        - "art"
        - "wine"
        - "variety_store"
        - "kiosk"
        - "second_hand"
        - "betting"
        - "lottery"
        - "tabacco"
        - "pawnbroker"
        - "bakery"
        - "butcher"
        - "greengrocer"
        - "hairdresser"
        - "beauty"
        - "optician"
        - "florist"
        - "dry_cleaning"
    business_economy:
      amenity:
        - "conference_centre"
        - "coworking_space"
        - "bank"
        - "bureau_de_change"
      office:
        - "company"
        - "coworking"
        - "government"
        - "lawyer"
        - "insurance"
        - "real_estate"
        - "architect"
        - "accountant"
        - "it"
        - "foundation"
        - "association"
      tourism:
        - "hotel"
        - "hostel"
        - "motel"
        - "guest_house"

# file paths
paths:
  raw: "data/raw"
  processed: "data/processed"
  viz: "data/viz"
  maps: "outputs/maps"

